version: '3.0'

services:

  nginx:
    container_name: 'nginx'
    image: 'nginx:latest'
    restart: 'always'
    ports:
      - 80:80
      - 443:443
    volumes: 
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - api

  postgres:
    container_name: 'postgres'
    image: 'postgres:latest'
    restart: 'always'
    ports:
      - 6000:5432
    environment:
      POSTGRES_PASSWORD: 'qwerty'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'awesomeblog'
    # volumes:
    #   - ./db/init.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    #   - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    container_name: 'server_app'
    restart: 'always'
    build: 
      dockerfile: 'Dockerfile'
      context: './server'
    ports:
      - 5000:5000
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - postgres