version: '3.0'

services:

  nginx:
    container_name: 'nginx'
    image: 'nginx:latest'
    restart: 'always'
    ports:
      - 4000:80
      # - 443:443
    volumes: 
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - pg
      - api

  pg:
    container_name: 'db'
    image: 'postgres:latest'
    restart: 'always'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: postgres
      POSTGRES_DB: 'AwesomeBlog'

  api:
    container_name: 'server_app'
    build: 
      dockerfile: 'Dockerfile'
      context: './server'
    volumes:
      - /app/node_modules
      - ./server:/app