version: '3.0'

services:

  nginx:
    container_name: 'nginx'
    image: 'nginx:latest'
    restart: 'always'
    network_mode: "host"
    ports:
      - 80:80
      - 443:443
    volumes: 
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './nginx/nginx-entrypoint.sh:/docker-entrypoint.d/nginx-entrypoint.sh:ro'
    # depends_on:
    #   - api

  postgres:
    container_name: 'postgres'
    image: 'postgres:latest'
    restart: 'always'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'qwerty'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'awesomeblog'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
